variables:
  S3_BUCKET_NAME: "yourbucket"

build:
  image: node:4.2.2
  script:
    - npm set progress=false
    - npm config set unsafe-perm true
    - npm -v
    - npm install --silent --production
    - npm install -g grunt-cli --silent --production
    - npm install grunt --silent --production
    - grunt prod
  cache:
      paths:
      - node_modules/

deploy:
  image: publysher/hugo
  script:
  - apt-get update
  - apt-get -qq install python python-pip ca-certificates
  - pip install awscli
  script:
  - hugo
  - aws s3 sync ./dist/ s3://$AWS_BUCKET
  only:
  - master